"""Publication labels; catalog identifiers and frozen numerical inputs stay intact."""

FAMILY_LABELS = {
    "aem-electrolyzer-oer": "AEM OER (anion-exchange-membrane oxygen evolution reaction)",
    "ammonia-cracking": "Ammonia cracking",
    "ammonia-synthesis": "Ammonia synthesis",
    "co2-electroreduction": "CO₂ electroreduction",
    "co2-methanation": "CO₂ methanation",
    "co2-methanol": "CO₂ hydrogenation to methanol",
    "co2-to-formate": "CO₂ hydrogenation to formate",
    "co-prox": "CO-PROX (preferential CO oxidation)",
    "dry-reforming": "DRM (dry reforming of methane)",
    "ethylene-epoxidation": "Ethylene epoxidation",
    "fischer-tropsch-synthesis": "FTS (Fischer–Tropsch synthesis)",
    "formic-acid-dehydrogenation": "Formic acid dehydrogenation",
    "fuel-cell-orr": "ORR (oxygen reduction reaction) in fuel cells",
    "glycerol-electrooxidation": "Glycerol electrooxidation",
    "hydrodeoxygenation": "HDO (hydrodeoxygenation)",
    "hydrogen-evolution-reaction": "HER (hydrogen evolution reaction)",
    "methane-pyrolysis": "Methane pyrolysis",
    "methanol-to-olefins": "MTO (methanol-to-olefins conversion)",
    "nh3-scr": "NH₃-SCR (selective catalytic reduction with ammonia)",
    "nitrogen-reduction-reaction": "NRR (nitrogen reduction reaction)",
    "olefin-metathesis": "Olefin metathesis",
    "pem-electrolyzer-oer": "PEM OER (proton-exchange-membrane oxygen evolution reaction)",
    "photocatalytic-co2-reduction": "Photocatalytic CO₂ reduction",
    "photocatalytic-water-splitting": "Photocatalytic water splitting",
    "propane-dehydrogenation": "PDH (propane dehydrogenation)",
    "rwgs": "RWGS (reverse water–gas shift)",
    "selective-acetylene-hydrogenation": "Selective acetylene hydrogenation",
    "steam-methane-reforming": "SMR (steam methane reforming)",
    "syngas-methanol": "Methanol synthesis from syngas",
    "water-gas-shift": "WGS (water–gas shift)",
}

STATUS_LABELS = {
    "screening_only": "No documented preparation",
    "source_mismatch": "Source/formulation discrepancy noted",
    "variant_available": "Source-specific preparation available",
}

# Use composition and structure rather than catalog marketing or ranking labels.
# Names identify screening models, not independently verified formulations.
CANDIDATE_LABELS = {
    "aem-electrolyzer-oer": {
        "cr-doped-amorphous": "Cr-doped amorphous NiFe",
        "nife-seed-assisted": "Seed-assisted NiFe",
        "nico2o4-spinel": "NiCo₂O₄ spinel",
        "nife-ldh-scalable": "NiFe layered double hydroxide",
    },
    "ammonia-cracking": {
        "co-mgo-la2o3": "Co/MgO–La₂O₃",
        "ni-mgo-ceo2-interface": "Ni–MgO/CeO₂ interface",
        "ni-alumina-baseline": "Ni/γ-Al₂O₃",
        "ru-mgo-premium": "Ru/MgO",
    },
    "ammonia-synthesis": {
        "cs-co3mo3n": "Cs-promoted Co₃Mo₃N",
        "fused-iron-baseline": "Promoted fused iron (magnetite/wüstite)",
        "ru-graphite-kaap": "Cs/Ba-promoted Ru on graphitized carbon",
        "ru-cafh-lowtemp": "Ru/CaFH",
    },
    "co2-electroreduction": {
        "ag-co-mea": "Ag cathode for CO production",
        "cu-multicarbon-co2rr": "Cu cathode for multicarbon products",
        "sn-formate-co2rr": "Sn cathode for formate production",
        "au-co-co2rr": "Au cathode for CO production",
    },
    "co2-methanation": {
        "ni-ceo2-lowtemp": "Ni/CeO₂",
        "ni-alumina-baseline": "Ni/Al₂O₃",
        "ru-layered-titanate": "Ru/layered titanate",
        "ru-mnox-photothermal": "Ru/MnOₓ",
    },
    "co2-methanol": {
        "cza-baseline": "Cu/ZnO/Al₂O₃",
        "cu-zrox-interface": "Cu/ZrOₓ–MgO interface",
        "in2o3-zro2-lowtemp": "In₂O₃–ZrO₂",
        "pd-in2o3": "Pd/In₂O₃",
    },
    "co2-to-formate": {
        "pdag-ndcarbon-co2fa": "PdAg on N-doped carbon",
        "ru-sa-ldh": "Single-atom Ru on Mg–Al layered double hydroxide",
        "ru-pincer-co2fa": "Ru pincer complex",
        "ir-pincer-co2fa": "Ir pincer complex",
    },
    "co-prox": {
        "cuo-ceo2": "CuO–CeO₂",
        "pt-fe-alumina": "Fe-promoted Pt/Al₂O₃",
        "au-tio2-nanogold": "Au/TiO₂ nanoparticles",
    },
    "dry-reforming": {
        "ni-co-almgo": "Ni–Co/Al–Mg–O",
        "ni-single-atom-ceria": "Ni/CeO₂ single sites",
        "ni-zeolite-stable": "Ni/zeolite",
        "ir-ceria-premium": "Ir@CeO₂₋ₓ",
    },
    "ethylene-epoxidation": {
        "agcs-industrial": "Ag–Cs/Al₂O₃",
        "ag-alumina-baseline": "Ag/α-Al₂O₃",
        "cu-ag-bimetallic": "Cu–Ag/α-Al₂O₃",
        "agcsre-modern": "Ag–Cs–Re/Al₂O₃",
    },
    "fischer-tropsch-synthesis": {
        "fe-silica-lower-olefin": "Fe/SiO₂",
        "fe-cu-k-precipitated": "Precipitated Fe–Cu–K",
        "co-alumina-fts": "Co/Al₂O₃",
        "co-cnt-structured": "Co on carbon nanotubes",
    },
    "formic-acid-dehydrogenation": {
        "co-nc-nonnoble": "Co single atoms/nanoparticles on N-doped carbon",
        "ptmo-gasphase-premium": "Pt–Mo ensembles",
        "pd-carbon-baseline": "Pd/C",
        "aupd-mil101": "Au–Pd in amine-grafted MIL-101",
    },
    "fuel-cell-orr": {
        "fen-c-pgmfree-cathode": "Fe–N–C cathode",
        "ptco-intermetallic-cathode": "Pt–Co intermetallic cathode",
        "ptc-baseline-cathode": "Pt/C cathode",
        "ptni-octahedra": "PtNi octahedra",
    },
    "glycerol-electrooxidation": {
        "niooh-glycerol-anode": "NiOOH anode",
        "pt-c-glycerol-anode": "Pt/C anode",
        "pt-bi-dha": "Pt–Bi anode for dihydroxyacetone production",
        "au-c-glycerol-selectivity": "Au/C anode",
    },
    "hydrodeoxygenation": {
        "comos-hdo": "CoMoS/Al₂O₃",
        "nimo-carbon-hdo": "NiMo/carbon",
        "pt-silica-hdo": "Pt/SiO₂",
        "ru-carbon-hdo": "Ru/C",
    },
    "hydrogen-evolution-reaction": {
        "nimo-alkaline-her-cathode": "NiMo cathode (alkaline)",
        "mos2-acidic-her-cathode": "MoS₂ cathode (acidic)",
        "pt-carbon-her-cathode": "Pt/C cathode",
        "ru-c2n-her": "Ru@C₂N cathode",
    },
    "methane-pyrolysis": {
        "activated-carbon-autocatalytic": "Activated carbon",
        "fe-alumina-pyrolysis": "Fe/Al₂O₃",
        "ni-sio2-highload": "Ni/SiO₂",
        "molten-ni-bi": "Molten Ni–Bi alloy",
    },
    "methanol-to-olefins": {
        "hzsm5-mth": "H-ZSM-5",
        "zn-zsm5-aromatics": "Zn/ZSM-5",
        "sapo-34-light-olefin": "SAPO-34 (chabazite)",
        "nano-sapo-34": "Nanosized SAPO-34",
    },
    "nh3-scr": {
        "v2o5-wo3-tio2": "V₂O₅–WO₃/TiO₂ monolith",
        "fe-zsm-5": "Fe-ZSM-5",
        "cu-ssz-13": "Cu-SSZ-13",
    },
    "nitrogen-reduction-reaction": {
        "li-mediated-nrr": "Li-mediated cathode",
        "plasma-nrr": "Plasma-assisted ammonia synthesis",
        "aqueous-nrr-cu": "Cu in aqueous electrolyte",
        "li-flow-shuttle": "Li-mediated flow cell with proton shuttle",
    },
    "olefin-metathesis": {
        "wo3-silica-oct": "WO₃/SiO₂",
        "mo-silica-alumina": "MoO₃/SiO₂–Al₂O₃",
        "w-h-alumina": "W–H/Al₂O₃ single-site hydride",
        "re2o7-alumina-mild": "Re₂O₇/Al₂O₃",
    },
    "pem-electrolyzer-oer": {
        "pem-low-ir-interface": "Low-Ir interface architecture",
        "pem-ru-rich-acidic": "Ru-rich anode",
        "iro2-tio2-supported": "IrO₂/TiO₂ anode",
        "pem-irox-baseline": "IrO₂ anode",
    },
    "photocatalytic-co2-reduction": {
        "tio2-photo-co2": "TiO₂",
        "gcn-sns2-zscheme": "g-C₃N₄/SnS₂ Z-scheme",
        "bivo4-visible": "Monoclinic BiVO₄",
        "cu2o-mof-co2": "Cu₂O/metal–organic framework heterojunction",
    },
    "photocatalytic-water-splitting": {
        "pt-tio2-cocatalyst": "Pt/TiO₂",
        "tio2-anatase-baseline": "TiO₂ (anatase)",
        "gcn-metal-free": "g-C₃N₄",
        "srtio3-al-qe-benchmark": "SrTiO₃:Al with Rh/Cr₂O₃ and CoOOH",
    },
    "propane-dehydrogenation": {
        "crox-alumina-catofin": "CrOₓ/Al₂O₃",
        "bn-odhp": "h-BN (oxidative dehydrogenation)",
        "ptsn-alumina-pdh": "Pt–Sn/Al₂O₃",
        "ptzn-intermetallic-pdh": "PtZn intermetallic/zeolite",
    },
    "rwgs": {
        "cu-ceria-baseline": "Cu/CeO₂",
        "mo2n-hightemp": "Mo₂N",
        "cs-fe-cu-alumina": "Cs–Fe–Cu/Al₂O₃",
        "pt-tio2-premium": "Pt/TiO₂",
    },
    "selective-acetylene-hydrogenation": {
        "nizn-intermetallic": "NiZn intermetallic",
        "pdcu-saa": "Pd–Cu single-atom alloy",
        "pd-alumina-baseline": "Pd/Al₂O₃",
        "pdag-bimetallic": "Pd–Ag bimetallic",
    },
    "steam-methane-reforming": {
        "ni-calcium-aluminate": "Ni on calcium aluminate",
        "sn-ni-coking-resistant": "Sn/Ni surface alloy",
        "rh-alumina-compact": "Rh/Al₂O₃",
    },
    "syngas-methanol": {
        "cza-industrial": "Cu/ZnO/Al₂O₃",
        "ga-promoted-cza": "Ga-promoted Cu/ZnO",
        "pd-zno-intermetallic": "Pd/ZnO intermetallic",
    },
    "water-gas-shift": {
        "cu-zno-baseline": "Cu/ZnO/Al₂O₃",
        "co-ceria-interface": "Co–CeO₂ interface",
        "fe-cr-hts": "Fe₂O₃–Cr₂O₃(–CuO)",
        "pt-ceria-premium": "Pt/CeO₂",
    },
}
